"""auto_migration

Revision ID: 00fca63243c8
Revises: c02e12487d73
Create Date: 2026-04-28 19:16:19.711868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00fca63243c8'
down_revision = 'c02e12487d73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('close_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'close_time')
    # ### end Alembic commands ###
