"""auto_migration

Revision ID: 05aa93a722eb
Revises: db8bd80cea74
Create Date: 2025-02-25 20:28:43.793546

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '05aa93a722eb'
down_revision = 'db8bd80cea74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('from_date', sa.Date(), nullable=True))
    op.add_column('menu', sa.Column('to_date', sa.Date(), nullable=True))
    op.drop_column('menu', 'date')
    op.drop_column('menu', 'freq_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('freq_id', postgresql.ENUM('FIX', 'DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY', name='frequency'), autoincrement=False, nullable=False))
    op.add_column('menu', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('menu', 'to_date')
    op.drop_column('menu', 'from_date')
    # ### end Alembic commands ###
