"""auto_migration

Revision ID: 0d3d892b399e
Revises: 10a258bbea8a
Create Date: 2026-02-05 22:13:20.253491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d3d892b399e'
down_revision = '10a258bbea8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_item', 'menu_item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order_item', 'size_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'order_item', 'menu_item', ['menu_item_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'order_item', 'size', ['size_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('user_basket_size_id_fkey', 'user_basket', type_='foreignkey')
    op.drop_constraint('fk_size_item', 'user_basket', type_='foreignkey')
    op.drop_constraint('user_basket_menu_item_id_fkey', 'user_basket', type_='foreignkey')
    op.create_foreign_key(None, 'user_basket', 'size', ['size_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_basket', 'menu_item', ['menu_item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_size_item', 'user_basket', 'size', ['size_id', 'menu_item_id'], ['id', 'menu_item_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_size_item', 'user_basket', type_='foreignkey')
    op.drop_constraint(None, 'user_basket', type_='foreignkey')
    op.drop_constraint(None, 'user_basket', type_='foreignkey')
    op.create_foreign_key('user_basket_menu_item_id_fkey', 'user_basket', 'menu_item', ['menu_item_id'], ['id'])
    op.create_foreign_key('fk_size_item', 'user_basket', 'size', ['size_id', 'menu_item_id'], ['id', 'menu_item_id'])
    op.create_foreign_key('user_basket_size_id_fkey', 'user_basket', 'size', ['size_id'], ['id'])
    op.drop_constraint(None, 'order_item', type_='foreignkey')
    op.drop_constraint(None, 'order_item', type_='foreignkey')
    op.alter_column('order_item', 'size_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order_item', 'menu_item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
