"""auto_migration

Revision ID: 10a258bbea8a
Revises: 35e96fc6e9de
Create Date: 2026-01-20 20:35:32.693647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10a258bbea8a'
down_revision = '35e96fc6e9de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_password_reset_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_password_reset_at')
    # ### end Alembic commands ###
