"""auto_migration

Revision ID: 2271110137f3
Revises: 9f84283c1a0d
Create Date: 2026-05-12 21:52:17.616143

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2271110137f3"
down_revision = "9f84283c1a0d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "category",
        sa.Column(
            "default_packaging_fee", sa.Integer(), server_default="0", nullable=False
        ),
    )
    op.add_column("menu_item", sa.Column("packaging_fee", sa.Integer(), nullable=True))
    op.add_column(
        "order_item",
        sa.Column("packaging_fee", sa.Integer(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order_item", "packaging_fee")
    op.drop_column("menu_item", "packaging_fee")
    op.drop_column("category", "default_packaging_fee")

    # ### end Alembic commands ###
