"""auto_migration

Revision ID: 35e96fc6e9de
Revises: 535fe3f3cbd3
Create Date: 2025-10-25 23:24:37.618128

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '35e96fc6e9de'
down_revision = '535fe3f3cbd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhooks', sa.Column('scheduled_days', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhooks', 'scheduled_days')
    # ### end Alembic commands ###
