"""auto_migration

Revision ID: 5323c1853979
Revises: f174537e3c8d
Create Date: 2025-07-15 22:35:25.752606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5323c1853979'
down_revision = 'f174537e3c8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'order_item', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_item', type_='unique')
    # ### end Alembic commands ###
