"""auto_migration

Revision ID: 56843ef892e0
Revises: 05aa93a722eb
Create Date: 2025-02-27 19:29:31.636589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56843ef892e0'
down_revision = '05aa93a722eb'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('size', sa.Column('unlimited', sa.Boolean(), nullable=False, server_default="true"))

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('size', 'unlimited')
    # ### end Alembic commands ###
