"""auto_migration

Revision ID: 88c657ad12be
Revises: 2271110137f3
Create Date: 2026-05-13 22:32:56.313050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88c657ad12be'
down_revision = '2271110137f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('size_id', sa.Integer(), nullable=False),
    sa.Column('quantity_change', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('ORDER', 'TOPUP', 'ADJUSTMENT', name='stockchangereason'), nullable=False),
    sa.Column('performed_by', sa.Uuid(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['performed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['size_id'], ['size.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stockhistory_size_id', 'stock_history', ['size_id'], unique=False)
    op.create_index('idx_stockhistory_timestamp', 'stock_history', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_stockhistory_timestamp', table_name='stock_history')
    op.drop_index('idx_stockhistory_size_id', table_name='stock_history')
    op.drop_table('stock_history')
    # ### end Alembic commands ###
