"""auto_migration

Revision ID: 8e15a67c05e2
Revises: 5cb1e0d19faf
Create Date: 2025-07-29 21:26:00.202915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e15a67c05e2'
down_revision = '5cb1e0d19faf'
branch_labels = None
depends_on = None


def upgrade():
    # Text search indexes for OrderItem (if item_name and size_label are in OrderItem)
    # First enable pg_trgm extension if not already enabled
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm;')



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
