"""auto_migration

Revision ID: 9f84283c1a0d
Revises: aaef5fa46b94
Create Date: 2026-05-12 20:30:01.738618

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9f84283c1a0d"
down_revision = "aaef5fa46b94"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "option_group",
        sa.Column("active", sa.Boolean(), nullable=False, server_default="true"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("option_group", "active")

    # ### end Alembic commands ###
