"""auto_migration

Revision ID: aaef5fa46b94
Revises: bd5f70ccfac6
Create Date: 2026-05-11 21:34:58.516304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaef5fa46b94'
down_revision = 'bd5f70ccfac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alembic_version_plugins')
    op.add_column('basket_option_selection', sa.Column('line_key', sa.String(), server_default='', nullable=False))
    op.drop_index('idx_bms_user_order', table_name='basket_option_selection')
    op.drop_constraint('uq_basket_option_selection', 'basket_option_selection', type_='unique')
    op.create_unique_constraint('uq_basket_option_selection', 'basket_option_selection', ['user_id', 'order_id', 'menu_item_id', 'size_id', 'line_key', 'option_choice_id'])
    op.add_column('user_basket', sa.Column('line_key', sa.String(), server_default='', nullable=False))
    op.drop_constraint('user_basket_pkey', 'user_basket', type_='primary')
    op.create_primary_key('user_basket_pkey', 'user_basket',
                          ['user_id', 'menu_item_id', 'size_id', 'order_id', 'line_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_basket_pkey', 'user_basket', type_='primary')
    op.create_primary_key('user_basket_pkey', 'user_basket',
                          ['user_id', 'menu_item_id', 'size_id', 'order_id'])
    op.drop_column('user_basket', 'line_key')
    op.drop_constraint('uq_basket_option_selection', 'basket_option_selection', type_='unique')
    op.create_unique_constraint('uq_basket_option_selection', 'basket_option_selection', ['user_id', 'order_id', 'menu_item_id', 'size_id', 'option_choice_id'])
    op.create_index('idx_bms_user_order', 'basket_option_selection', ['user_id', 'order_id'], unique=False)
    op.drop_column('basket_option_selection', 'line_key')
    op.create_table('alembic_version_plugins',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_plugins_pkc')
    )
    # ### end Alembic commands ###
