"""auto_migration

Revision ID: b3fa6e8019f4
Revises: def98278fcee
Create Date: 2024-12-11 21:43:58.020984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3fa6e8019f4'
down_revision = 'def98278fcee'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=False, server_default="false"))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'admin')
    # ### end Alembic commands ###
