"""auto_migration

Revision ID: bd5f70ccfac6
Revises: 00fca63243c8
Create Date: 2026-05-06 08:09:19.584707

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "bd5f70ccfac6"
down_revision = "00fca63243c8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bundle_discount",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("vendor_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["vendor_id"], ["vendor.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "option_group",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("vendor_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("min_choices", sa.Integer(), nullable=False),
        sa.Column("max_choices", sa.Integer(), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["vendor_id"], ["vendor.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "option_choice",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("option_group_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("price_delta", sa.Integer(), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["option_group_id"], ["option_group.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "basket_option_selection",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("menu_item_id", sa.Integer(), nullable=False),
        sa.Column("size_id", sa.Integer(), nullable=False),
        sa.Column("option_choice_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["option_choice_id"], ["option_choice.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["order_id"], ["order.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "order_id",
            "menu_item_id",
            "size_id",
            "option_choice_id",
            name="uq_basket_option_selection",
        ),
    )
    op.create_table(
        "bundle_slot",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("bundle_discount_id", sa.Integer(), nullable=False),
        sa.Column("slot_index", sa.Integer(), nullable=False),
        sa.Column("match_type", sa.String(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("menu_item_id", sa.Integer(), nullable=True),
        sa.Column("price_override", sa.Integer(), nullable=True),
        sa.Column("price_delta", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bundle_discount_id"], ["bundle_discount.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["category_id"], ["category.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["menu_item_id"], ["menu_item.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "option_group_item",
        sa.Column("option_group_id", sa.Integer(), nullable=False),
        sa.Column("menu_item_id", sa.Integer(), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["menu_item_id"], ["menu_item.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["option_group_id"], ["option_group.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("option_group_id", "menu_item_id"),
    )
    op.add_column(
        "order_item",
        sa.Column(
            "extras_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.create_index(
        "idx_bms_user_order", "basket_option_selection", ["user_id", "order_id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_bms_user_order", table_name="basket_option_selection")
    op.drop_column("order_item", "extras_summary")
    op.drop_table("option_group_item")
    op.drop_table("bundle_slot")
    op.drop_table("basket_option_selection")
    op.drop_table("option_choice")
    op.drop_table("option_group")
    op.drop_table("bundle_discount")
    # ### end Alembic commands ###
