"""auto_migration

Revision ID: c7d8a55dd1f4
Revises: 7f1bee4584b3
Create Date: 2026-03-16 21:28:09.832644

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c7d8a55dd1f4"
down_revision = "7f1bee4584b3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE notificationtype ADD VALUE IF NOT EXISTS 'FAVOURITE'")
    op.create_table(
        "user_favourite",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("vendor_id", sa.Uuid(), nullable=False),
        sa.Column("item_name", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendor.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # Migrate notification table: replace single notification_type column with
    # notification_types array so one device subscription covers multiple types.
    notificationtype_enum = postgresql.ARRAY(
        sa.Enum(
            "CLOSING",
            "REMINDER",
            "FAVOURITE",
            name="notificationtype",
            create_type=False,
        )
    )
    op.add_column(
        "notification",
        sa.Column("notification_types", notificationtype_enum, nullable=True),
    )
    op.execute("UPDATE notification SET notification_types = ARRAY[notification_type]")
    op.alter_column("notification", "notification_types", nullable=False)
    op.drop_column("notification", "notification_type")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_favourite")
    # PostgreSQL does not support removing enum values — 'FAVOURITE' is left in the type as an unused value.
    # Restore single-type column (takes first element from the array)
    op.add_column(
        "notification",
        sa.Column(
            "notification_type",
            sa.Enum(
                "CLOSING",
                "REMINDER",
                "FAVOURITE",
                name="notificationtype",
                create_type=False,
            ),
            nullable=True,
        ),
    )
    op.execute("UPDATE notification SET notification_type = notification_types[1]")
    op.alter_column("notification", "notification_type", nullable=False)
    op.drop_column("notification", "notification_types")
    # ### end Alembic commands ###
